name: 自动上传京东互助码
on:
  schedule:
    - cron: '10 18 9,19,28-31 * *'
  workflow_dispatch:
jobs:
  jdJob:
    runs-on: ubuntu-latest
    env:
      TG_USER_ID: ${{ secrets.TG_USER_ID }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      PUSH_KEY: ${{ secrets.PUSH_KEY }}
      MyFruit1: ${{ secrets.MyFruit1 }}
      MyFruit2: ${{ secrets.MyFruit2 }}
      MyBean1: ${{ secrets.MyBean1 }}
      MyBean2: ${{ secrets.MyBean2 }}
      MyPet1: ${{ secrets.MyPet1 }}
      MyPet2: ${{ secrets.MyPet2 }}
      MyDreamFactory1: ${{ secrets.MyDreamFactory1 }}
      MyDreamFactory2: ${{ secrets.MyDreamFactory2 }}
      MyJdFactory1: ${{ secrets.MyJdFactory1 }}
      MyJdFactory2: ${{ secrets.MyJdFactory2 }}
      MyJdzz1: ${{ secrets.MyJdzz1 }}
      MyJdzz2: ${{ secrets.MyJdzz2 }}
      MyJoy1: ${{ secrets.MyJoy1 }}
      MyJoy2: ${{ secrets.MyJoy2 }}
      MyCash1: ${{ secrets.MyCash1 }}
      MyCash2: ${{ secrets.MyCash2 }}
    steps:
      - name: "京东农场互助码1上传"
        if: env.MyFruit1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/farm/create/${{ env.MyFruit1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "京东农场互助码2上传"
        if: env.MyFruit2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/farm/create/${{ env.MyFruit2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "种豆得豆互助码1上传"
        if: env.MyBean1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/bean/create/${{ env.MyBean1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "种豆得豆互助码2上传"
        if: env.MyBean2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/bean/create/${{ env.MyBean2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "东东萌宠互助码1上传"
        if: env.MyPet1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/pet/create/${{ env.MyPet1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "东东萌宠互助码2上传"
        if: env.MyPet2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/pet/create/${{ env.MyPet2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "京喜工厂互助码1上传"
        if: env.MyDreamFactory1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/jxfactory/create/${{ env.MyDreamFactory1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "京喜工厂互助码2上传"
        if: env.MyDreamFactory2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/jxfactory/create/${{ env.MyDreamFactory2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "东东工厂互助码1上传"
        if: env.MyJdFactory1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/ddfactory/create/${{ env.MyJdFactory1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "东东工厂互助码2上传"
        if: env.MyJdFactory2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl http://api.turinglabs.net/api/v1/jd/ddfactory/create/${{ env.MyJdFactory2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "京东赚赚互助码1上传"
        if: env.MyJdzz1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl https://code.chiang.fun/api/v1/jd/jdzz/create/${{ env.MyJdzz1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "京东赚赚互助码2上传"
        if: env.MyJdzz2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl https://code.chiang.fun/api/v1/jd/jdzz/create/${{ env.MyJdzz2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "疯狂的Joy互助码1上传"
        if: env.MyJoy1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/${{ env.MyJoy1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "疯狂的Joy互助码2上传"
        if: env.MyJoy2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl https://code.chiang.fun/api/v1/jd/jdcrazyjoy/create/${{ env.MyJoy2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "签到领现金互助码1上传"
        if: env.MyCash1
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl https://code.chiang.fun/api/v1/jd/jdcash/create/${{ env.MyCash1 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: "签到领现金互助码2上传"
        if: env.MyCash2
        run: |
          returnCode=0; \
          while (($returnCode != 400)); \
          do \
            returnCode=`curl https://code.chiang.fun/api/v1/jd/jdcash/create/${{ env.MyCash2 }}/ | sed 's/ //g' | grep -Po '(?<="code":)[0-9]+'`; \
            echo "returnCode="$returnCode; \
          done;
      - name: Notify To Telegram
        if: env.TG_USER_ID && env.TG_BOT_TOKEN
        run: |
          curl -s -o /dev/null -X POST https://api.telegram.org/bot${{ env.TG_BOT_TOKEN }}/sendMessage \
          -H "Content-Type: application/json" \
          --data '{"text": "${{github.workflow}}完成！","chat_id": "${{ env.TG_USER_ID }}"}'
      - name: Notify To Server酱
        if: env.PUSH_KEY
        run: |
          curl -s -o /dev/null -X POST https://sc.ftqq.com/${{ env.PUSH_KEY }}.send \
          -H "Content-Type: application/x-www-form-urlencoded" \
          --data 'text=${{ github.workflow }}完成！&desp=${{ github.workflow }}完成！'
